# Repaso de NumPy

- Qué es un arreglo de NumPy
- Propiedades básicas del arreglo
- Creación de arreglos
- Acceso a elementos y slicing
- Operaciones matemáticas
- Operaciones estadísticas
- Filtros booleanos
- Manejo de valores faltantes con `NaN`


In [ ]:
import numpy as np

## 1. ¿Qué es un arreglo de NumPy?

Un arreglo de NumPy es una estructura diseñada para almacenar datos numéricos de forma eficiente.  
A diferencia de una lista de Python, un arreglo suele trabajar mejor cuando todos sus elementos tienen el mismo tipo y cuando queremos hacer cálculos sobre muchos valores a la vez.



In [ ]:
valores = np.array([18.5, 22.1, 19.8, 25.4, 21.0, 17.6])

print("Arreglo:", valores)
print("Tipo del objeto:", type(valores))
print("Tipo de los datos:", valores.dtype)

Arreglo: [18.5 22.1 19.8 25.4 21.  17.6]
Tipo del objeto: <class 'numpy.ndarray'>
Tipo de los datos: float64


In [ ]:
valores = np.array(["Pedro", True, 20, 10.0])
print(valores.dtype)
print(valores)

<U32
['Pedro' 'True' '20' '10.0']


## 2. Propiedades básicas

Para conocer conocer la estructura del arreglo


- `shape`: forma del arreglo
- `ndim`: número de dimensiones
- `size`: número total de elementos
- `dtype`: tipo de dato almacenado


In [ ]:
#Cada valor de la matrix representa un nivel de contaminación del aire
calidad_aire = np.array([
    [42, 38, 35, 40],
    [55, 60, 58, 62],
    [30, 28, 27, 31]
])

print("Matriz de calidad del aire:")
print(calidad_aire)
print("shape:", calidad_aire.shape) #Se accede a una propiedad del arreglo
print("ndim:", calidad_aire.ndim)
print("size:", calidad_aire.size)
print("dtype:", calidad_aire.dtype)

Matriz de calidad del aire:
[[42 38 35 40]
 [55 60 58 62]
 [30 28 27 31]]
shape: (3, 4)
ndim: 2
size: 12
dtype: int64


Esta matriz tiene:

- 3 filas: tres ciudades
- 4 columnas: cuatro valores que representan que tan contaminada esta esa ciudad.


## 3. Creación de arreglos


In [ ]:
# Alquileres de bicicletas previstos para 7 días
alquileres_bicicletas = np.array([120, 135, 142, 128, 150, 167, 160]) # Se pasa como parámetro una lista
print("alquileres_bicicletas:", alquileres_bicicletas)

# Stock de emergencia inicializado en cero
stock_emergencia = np.zeros((3, 4))
print("stock_emergencia:\n", stock_emergencia)

stock_emergencia[0][2] = 3
print("stock_emergencia:\n", stock_emergencia)

# Matriz de inspección con todos los sistemas activos
estado_sistemas = np.ones((2, 5))
print("estado_sistemas:\n", estado_sistemas)

arreglo_unidimensional = np.ones(10)
print("Arreglo de una dimensión: ", arreglo_unidimensional)

# Una tarifa constante para 6 meses
#tarifa_mensual = np.full(6, 49.99)
#print("tarifa_mensual:", tarifa_mensual)

# Franjas horarias cada 2 horas durante un día
#franjas_horarias = np.arange(0, 24, 3) # (a,b, step)
#print("franjas_horarias:", franjas_horarias)

# Genera 8 valores en el intervalo 0,100
#marcas_progreso = np.linspace(0, 100, 8)
#print("marcas_progreso:\n", marcas_progreso)

np.random.seed(42) # Semilla para generar el mismo arreglo, con los mismos valores cada que se ejecuta el código
tiempos_espera = np.random.randint(3, 21, size=10)
print("tiempos_espera:", tiempos_espera)

alquileres_bicicletas: [120 135 142 128 150 167 160]
stock_emergencia:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
stock_emergencia:
 [[0. 0. 3. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
estado_sistemas:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo de una dimensión:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tiempos_espera: [ 9 17 13 10  9 13 13  6 10  5]


## 4. Acceso a elementos y slicing

El acceso por índice nos permite extraer un valor específico, una fila, una columna o un bloque del arreglo.

En este ejemplo, cada fila representa una ruta de reparto y cada columna representa un tramo del recorrido medido en kilómetros.

In [ ]:
rutas_reparto = np.array([
    [4.2, 5.1, 3.8, 6.0], #fila representa una ruta de reparto
    [7.5, 2.4, 4.1, 5.6], #columna: tramo del recorrido
    [3.3, 3.9, 4.8, 2.7]
])

print("Matriz completa:")
print(rutas_reparto)
#print("\nPrimer valor de la primera ruta:", rutas_reparto[0, 0])
#print("Último tramo de la segunda ruta:", rutas_reparto[1, -1]) # Fila 1 , Columna: -1 -a la última
#print("Primera ruta completa:", rutas_reparto[0])
#print("Segunda ruta completa:", rutas_reparto[1])
#print("Tercer ruta completa:", rutas_reparto[2])
#print("Todos los primeros tramos:", rutas_reparto[:, 0]) #[ filas, columnas]
#print("Todos los primeros tramos:", rutas_reparto[0:3, 0:2]) #[ posisicones de las filas, posiciones de las columnas]
#?# rutas_reparto[0:3, 0:2]
print("Submatriz con las dos primeras rutas y los dos últimos tramos:")
# Tomar las primeras 2 filas
# y desde la tercera columna hasta el final
print(rutas_reparto[0:2, 2:4])  # Notación más explícita
print(rutas_reparto[0:2, -2:])  #AlternativaTener cuidado con los -
print(rutas_reparto[:2, 2:])   # [desdel inicio hasta la posicion 1, desde la posición 2 hasta el resto]

Matriz completa:
[[4.2 5.1 3.8 6. ]
 [7.5 2.4 4.1 5.6]
 [3.3 3.9 4.8 2.7]]
Submatriz con las dos primeras rutas y los dos últimos tramos:
[[3.8 6. ]
 [4.1 5.6]]
[[3.8 6. ]
 [4.1 5.6]]
[[3.8 6. ]
 [4.1 5.6]]



- `arreglo[fila, columna]` accede a un elemento exacto
- `arreglo[0]` devuelve la primera fila
- `arreglo[:, 0]` devuelve la primera columna
- `arreglo[inicio:fin]` permite tomar un rango

## 5. Operaciones matemáticas

Una de las grandes ventajas de NumPy es que permite operar con todos los elementos del arreglo de una sola vez.

Supongamos que tenemos consumo energético diario en kilovatios-hora (`kWh`) de dos edificios y queremos compararlo.

In [ ]:
#edificio_a = np.array([320, 340, 310, 355, 370, 85,90]) error: deben de ser del mismo tamaño ambos arreglos
#edificio_b = np.array([300, 335, 295, 348, 365])

edificio_a = np.array([320, 340, 310, 355, 370])
edificio_b = np.array([300, 335, 295, 348, 365])

diferencia = edificio_a - edificio_b
total = edificio_a + edificio_b

escalado_a = edificio_a * 1.08

promedio_pareja = (edificio_a + edificio_b) / 2

print("Diferencia:", diferencia)
print("Consumo total:", total)
print("Edificio A con aumento del 8%:", escalado_a)
print("Promedio entre edificios:", promedio_pareja)
##??

Diferencia: [20  5 15  7  5]
Consumo total: [620 675 605 703 735]
Edificio A con aumento del 8%: [345.6 367.2 334.8 383.4 399.6]
Promedio entre edificios: [310.  337.5 302.5 351.5 367.5]


## 6. Operaciones estadísticas

NumPy incluye funciones datos rápidamente.

En el siguiente ejemplo analizamos el número de visitantes en un museo, donde cada fila representa una sala y cada columna una hora del día.

In [ ]:
visitantes_museo = np.array([
    [1,  1, 49, 60],  #Fila: sala
    [30, 28, 35, 42],  #Columna: hora del dia
    [55, 58, 61, 66]
])
#print("Total general:", np.sum(visitantes_museo))
#print("Promedio general:", np.mean(visitantes_museo))
#print("Valor mínimo:", np.min(visitantes_museo))
#print("Valor máximo:", np.max(visitantes_museo))
#print("Desviación estándar:", np.std(visitantes_museo))
print("\nTotal por sala (filas):", np.sum(visitantes_museo, axis=1)) #Suma de filas  [1 + 1 + 49 + 60, 30+28+35+42, 55+58+61+66]
print("Total por hora (columnas):", np.sum(visitantes_museo, axis=0)) # Suma por columnas [1+30+55, 1+28+58, 49+35+61, 60+42+66]
print("Promedio por sala:", np.mean(visitantes_museo, axis=1)) #Promedio por filas
print("Promedio por hora:", np.mean(visitantes_museo, axis=0)) # Promedio por columnas


Total por sala (filas): [111 135 240]
Total por hora (columnas): [ 86  87 145 168]
Promedio por sala: [27.75 33.75 60.  ]
Promedio por hora: [28.66666667 29.         48.33333333 56.        ]


La desviación estándar mide la dispersión de los datos.
Entre mayor sea, más separados están de la media; entre menor sea, más cerca están del promedio.

`axis`
- `axis=0`: recorre hacia abajo y resume por columnas
- `axis=1`: recorre hacia la derecha y resume por filas



## 7. Filtros booleanos

Los filtros booleanos sirven para seleccionar solo los datos que cumplen una condición.

Trabajaremos con tiempos de respuesta de un servicio en línea medidos en milisegundos.

In [ ]:
tiempos_respuesta = np.array([180, 220, 145, 310, 275, 198, 405, 167, 250])

filtro_respuestas_lentas = tiempos_respuesta > 250
filtro_ventana_normal = (tiempos_respuesta >= 150) & (tiempos_respuesta <= 250)

print("Filtro de respuestas lentas:", filtro_respuestas_lentas)
print("Respuestas lentas:", tiempos_respuesta[filtro_respuestas_lentas])

print("Respuestas dentro del rango normal:", tiempos_respuesta[filtro_ventana_normal])
print("Clasificación con np.where:")
print(np.where(tiempos_respuesta > 300, "critico", "aceptable")) # (filtro o condicion, condicion = True coloco "Critico", condicion = False coloco Aceptable)

Filtro de respuestas lentas: [False False False  True  True False  True False False]
Respuestas lentas: [310 275 405]
Respuestas dentro del rango normal: [180 220 198 167 250]
Clasificación con np.where:
['aceptable' 'aceptable' 'aceptable' 'critico' 'aceptable' 'aceptable'
 'critico' 'aceptable' 'aceptable']


### Nota
Primero generamos una condición que produce `True` o `False`.  
Después usamos esa condición para quedarnos solo con los valores que nos interesan.

## 8. Manejo de valores faltantes con `NaN`

En datos reales es muy común encontrar registros faltantes.  
NumPy representa estos valores como `NaN` (`Not a Number`).

En este ejemplo, una red de sensores registra niveles de humedad, pero algunos sensores fallaron temporalmente.

In [ ]:
humedad = np.array([58.0, 61.5, np.nan, 63.2, 59.8, np.nan, 60.1])

print("Datos originales:", humedad)
print("¿Dónde hay NaN?:", np.isnan(humedad))
print("Suma ignorando NaN:", np.nansum(humedad))
print("Promedio ignorando NaN:", np.nanmean(humedad))
print("Mínimo ignorando NaN:", np.nanmin(humedad))
print("Máximo ignorando NaN:", np.nanmax(humedad))
print("Reemplazo de NaN por 0:", np.nan_to_num(humedad, nan=0))

Datos originales: [58.  61.5  nan 63.2 59.8  nan 60.1]
¿Dónde hay NaN?: [False False  True False False  True False]
Suma ignorando NaN: 302.6
Promedio ignorando NaN: 60.52
Mínimo ignorando NaN: 58.0
Máximo ignorando NaN: 63.2
Reemplazo de NaN por 0: [58.  61.5  0.  63.2 59.8  0.  60.1]


## 9. Reemplazo condicional con `np.where`
Remplazar los nan por el promedio

In [ ]:
promedio_humedad = np.nanmean(humedad)
humedad_completada = np.where(np.isnan(humedad), promedio_humedad, humedad)

print("Promedio usado para reemplazar:", promedio_humedad)
print("Serie completada:", humedad_completada)

Promedio usado para reemplazar: 60.52
Serie completada: [58.   61.5  60.52 63.2  59.8  60.52 60.1 ]


### Ejercicio
Se tienen las siguientes temperaturas

`[3.7, 3.6, np.nan, 3.8, 3.7, np.nan, 3.9]`

Obten:
- los valores que no son `NaN`
- el promedio ignorando `NaN`
- la serie reemplazando los faltantes por el promedio

In [ ]:
voltaje = np.array([3.7, 3.6, np.nan, 3.8, 3.7, np.nan, 3.9])

print("Filtro NaN:", np.isnan(voltaje))
print("Promedio sin NaN:", np.nanmean(voltaje))
print("Serie completada:", np.where(np.isnan(voltaje), np.nanmean(voltaje), voltaje))