## Numpy: Reorganización y combinación de arreglos

Documentación Oficial de Numpy
 - https://numpy.org/

Documentación Oficial de Python
 - https://docs.python.org/3/tutorial/index.html


In [1]:
import numpy as np

In [3]:
ventas = np.array([18, 20, 17, 22, 25, 24, 21, 23, 19, 18, 20, 22])

In [4]:
print(ventas)

[18 20 17 22 25 24 21 23 19 18 20 22]


In [5]:
ventas.shape

(12,)

In [6]:
ventas_tablero =  ventas.reshape(3,4)
print("Ventas_tablero\n", ventas_tablero)

Ventas_tablero
 [[18 20 17 22]
 [25 24 21 23]
 [19 18 20 22]]


In [9]:
ventas_tablero =  ventas.reshape(1,12)
print(ventas_tablero)

[[18 20 17 22 25 24 21 23 19 18 20 22]]


In [11]:
ventas_tablero =  ventas.reshape(4,3)
print(ventas_tablero)

[[18 20 17]
 [22 25 24]
 [21 23 19]
 [18 20 22]]


In [12]:
ventas_tablero =  ventas.reshape(2,6)
print(ventas_tablero)

[[18 20 17 22 25 24]
 [21 23 19 18 20 22]]


In [13]:
ventas_tablero_aplanado = ventas_tablero.flatten()
print(ventas_tablero_aplanado)

[18 20 17 22 25 24 21 23 19 18 20 22]


In [15]:
datos = np.arange(1, 7).reshape(2,3)
print(datos)



[[1 2 3]
 [4 5 6]]


In [26]:
# Uso de -1 en reshape 
entregas = np.array([18, 20, 17, 22, 25, 24, 21, 23, 19, 18, 20, 22])
print(entregas)
print("Cantidad de elementos: " , entregas.size)
print("Cantidad de elementos: " , len(entregas))

[18 20 17 22 25 24 21 23 19 18 20 22]
Cantidad de elementos:  12
Cantidad de elementos:  12


In [27]:
print(entregas.reshape(3, 4)) #-1: Numpy infiere la cantidad necesaria de columnas

[[18 20 17 22]
 [25 24 21 23]
 [19 18 20 22]]


In [28]:
print(entregas.reshape(3, -1)) #

[[18 20 17 22]
 [25 24 21 23]
 [19 18 20 22]]


In [35]:
columnas = (entregas.size / 3)  #Genera un número float o decimal , por lo tnato no podemos usarlo como entrada en el reshape
print(int(columnas))
print(entregas.reshape(3, int(columnas))) 

4
[[18 20 17 22]
 [25 24 21 23]
 [19 18 20 22]]


## Transformación de matrices

In [36]:
mediciones_horas = np.array([
    [12, 15, 11, 14], #Mexico
    [18, 17, 16, 19], #Colobia
    [10, 12, 13, 11]  #Argentina
])

In [38]:
print(mediciones_horas )

[[12 15 11 14]
 [18 17 16 19]
 [10 12 13 11]]


In [37]:
print(mediciones_horas.shape)

(3, 4)


In [40]:
medicion_horas_transpuesta = mediciones_horas.T
print(medicion_horas_transpuesta)
print("Shape: ", medicion_horas_transpuesta.shape)

[[12 18 10]
 [15 17 12]
 [11 16 13]
 [14 19 11]]
Shape:  (4, 3)


## Aplanado de un arreglo

In [44]:
mediciones_horas = np.array([
    [12, 15, 11, 14], #Mexico
    [18, 17, 16, 19], #Colobia
    [10, 12, 13, 11]  #Argentina
])

aplanado_horas = mediciones_horas.flatten()
print("Uso de flatten \n", aplanado_horas)
print("Dimensiones \n", aplanado_horas.shape)
print("Tamaño \n", aplanado_horas.size)


Uso de flatten 
 [12 15 11 14 18 17 16 19 10 12 13 11]
Dimensiones 
 (12,)
Tamaño 
 12


In [45]:
aplando_horas = mediciones_horas.ravel()
print("Uso de flatten \n", aplanado_horas)
print("Dimensiones \n", aplanado_horas.shape)
print("Tamaño \n", aplanado_horas.size)

Uso de flatten 
 [12 15 11 14 18 17 16 19 10 12 13 11]
Dimensiones 
 (12,)
Tamaño 
 12


## Broadcasting

In [47]:
precios_entradas = np.array([12.5, 15.0, 18.0, 22.0])

precios_entradas_actualizados = precios_entradas + 1.5
print(precios_entradas_actualizados)

[14.  16.5 19.5 23.5]


In [48]:
ventas = np.array([
    [1200, 1350, 1280, 1400],
    [980, 1025, 1100, 1080],
    [1500, 1475, 1520, 1600]
])
print(ventas)

[[1200 1350 1280 1400]
 [ 980 1025 1100 1080]
 [1500 1475 1520 1600]]


In [52]:
#ajuste_promocion = np.array([50, 30, 20, 40,20,20])
ajuste_promocion = np.array([50, 30, 20, 40]) # El número de elementos del arreglo, debe de ser igual al número de columnas de la matriz
nuevas_ventas = ventas + ajuste_promocion

print(nuevas_ventas)

[[1250 1380 1300 1440]
 [1030 1055 1120 1120]
 [1550 1505 1540 1640]]


In [55]:
ventas_sucursal =  np.array([100,80,120]).reshape(3,1)
print(ventas_sucursal)

[[100]
 [ 80]
 [120]]


In [58]:
print("Ventas originales:\n ", ventas)
resta_ventas = ventas - ventas_sucursal
print("Resta de ventas: \n", resta_ventas)
print("Shape de resta de ventas: ", resta_ventas.shape)

Ventas originales:
  [[1200 1350 1280 1400]
 [ 980 1025 1100 1080]
 [1500 1475 1520 1600]]
Resta de ventas: 
 [[1100 1250 1180 1300]
 [ 900  945 1020 1000]
 [1380 1355 1400 1480]]
Shape de resta de ventas:  (3, 4)


In [59]:
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

vector_valido = np.array([10, 20, 30, 40])  # Sumar un arreglo a todos los elementos de la matriz

print(matriz + vector_valido)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


## Combinación de arreglos

In [64]:
valores_a = np.array([21.5, 22.0, 21.8, 22.4, 10, 2])
valores_b = np.array([22.1, 22.3, 22.0, 21.9])

In [66]:

temperaturas = np.concatenate([valores_a, valores_b])
print("Concatenación de temperaturas: ",temperaturas)
print("Size: ", temperaturas.size)


Concatenación de temperaturas:  [21.5 22.  21.8 22.4 10.   2.  22.1 22.3 22.  21.9]
Size:  10


In [67]:
region_norte = np.array([
    [15, 18, 17],
    [20, 22, 21]
])

region_sur = np.array([
    [25, 24, 26],
    [19, 18, 20]
])


In [73]:
apilado_vertical = np.vstack([region_norte, region_sur]) # Unión de dos matrices de forma vertical
print("Apilado vertical: \n", apilado_vertical)
print("Sahpe: ", apilado_vertical.shape)

Apilado vertical: 
 [[15 18 17]
 [20 22 21]
 [25 24 26]
 [19 18 20]]
Sahpe:  (4, 3)


In [71]:
turno_manana = np.array([
    [42, 38],
    [35, 40],
    [50, 47]
])

turno_tarde = np.array([
    [39, 41],
    [36, 37],
    [48, 46]
])

In [74]:
apilado_horizontal = np.hstack([turno_manana, turno_tarde])
print("Matriz apilada horizontalmente: \n",apilado_horizontal)
print("Shape: ", apilado_horizontal.shape)

Matriz apilada horizontalmente: 
 [[42 38 39 41]
 [35 40 36 37]
 [50 47 48 46]]
Shape:  (3, 4)


Nota: 
 - vstack(): Va aumentar el número de filas
 - hstack(): Va aumentar el número de columnas

## Dividir un arreglo (Split)

In [75]:
edad = np.array([11, 13, 15, 14, 16, 18, 17, 19, 21, 20, 22, 24])

print("Edad :\n", edad )
print("Tamanño: ", edad.size)


Edad :
 [11 13 15 14 16 18 17 19 21 20 22 24]
Tamanño:  12


In [77]:
arreglo_dividido = np.split(edad, 4) #[array([11, 13, 15]), array([14, 16, 18]), array([17, 19, 21]), array([20, 22, 24])]
print(arreglo_dividido)

[array([11, 13, 15]), array([14, 16, 18]), array([17, 19, 21]), array([20, 22, 24])]


In [78]:
print("Tipo del arreglo_dividido: ", type(arreglo_dividido))

Tipo del arreglo_dividido:  <class 'list'>


In [80]:
primer_arreglo = arreglo_dividido[0] #Corresponde al primer arreglo de la lista que es: [11 13 15]
print("El primer arreglo es: ", primer_arreglo)
print("Tipo de dato del primer arreglo ", type(primer_arreglo))

El primer arreglo es:  [11 13 15]
Tipo de dato del primer arreglo  <class 'numpy.ndarray'>


In [81]:
segundo_arreglo = arreglo_dividido[1] #Corresponde a la segunda posición del arreglo
print("El segundo arreglo es: ", segundo_arreglo ) 
print("Tipo de dato del segundo arreglo ", type(segundo_arreglo ))

El segundo arreglo es:  [14 16 18]
Tipo de dato del segundo arreglo  <class 'numpy.ndarray'>


In [82]:
tercer_arreglo = arreglo_dividido[2] #Corresponde a la segunda posición del arreglo
print("El tercer arreglo es: ", tercer_arreglo ) 
print("Tipo de dato del tercer arreglo ", type(tercer_arreglo))

El tercer arreglo es:  [17 19 21]
Tipo de dato del tercer arreglo  <class 'numpy.ndarray'>


## Ejercicios

### Ejercicio 01
Usa broadcasting para sumar el vector `[5, 10, 15]` a cada fila de la matriz siguiente:

```python
[[20, 25, 30],
 [35, 40, 45]]
```

In [92]:
matriz_base = np.array([
    [20, 25, 30],
    [35, 40, 45]
])

#incremento = np.array([5, 10, 15,10])
incremento = np.array([5, 10, 15])

tupla = matriz_base.shape
print("Tipo de datos: ", type(tupla))
numero_columnas_matriz_base = tupla[1] # 1 corresponde al número de columnas
print(numero_columnas_matriz_base)

if (tupla[1] == incremento.size ): # Número de columnas == cantidad de elementos del arreglo
    suma_vector = matriz_base + incremento
    print(suma_vector)
else:
    print("No se puede efectuar la operación")

Tipo de datos:  <class 'tuple'>
3
[[25 35 45]
 [40 50 60]]


In [94]:
def suma_broadcasting(matriz ,  vector):
    tupla = matriz.shape

    if (tupla[1] == vector.size):
        suma_vector = matriz + vector
        return suma_vector
    else: 
        print("No se peude efectuar la operación")
        return None
    

In [95]:
matriz_base = np.array([
    [20, 15, 3],
    [75, 30, 5]
])
incremento = np.array([5, 10, 15])

# Mandar a llamar a la función suma_broadcasting
suma_broadcasting(matriz_base, incremento)


array([[25, 35, 45],
       [40, 50, 60]])

## Datos desde un archivo de texto

In [99]:
txt_data = np.loadtxt("numeros.txt")
print(txt_data)

print("Tipo de dato de txt: ",type(txt_data))

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
Tipo de dato de txt:  <class 'numpy.ndarray'>


In [102]:
csv_data = np.loadtxt("numeros.csv", delimiter=",")
print(csv_data)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
